package com.mddiet.pro;
import android.app.*;import android.content.*;import android.os.Build;import java.util.Calendar;
public class NotificationScheduler {
 public static final String CHANNEL_ID="meal_reminders_v2",WATER_CHANNEL_ID="water_reminders_v2";
 public static void createChannels(Context c){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);n.createNotificationChannel(new NotificationChannel(CHANNEL_ID,"تذكير الوجبات",NotificationManager.IMPORTANCE_HIGH));n.createNotificationChannel(new NotificationChannel(WATER_CHANNEL_ID,"تذكير شرب الماء",NotificationManager.IMPORTANCE_DEFAULT));}}
 public static void scheduleAll(Context c){scheduleMeal(c,0,"breakfast","08:00");scheduleMeal(c,1,"snack","13:00");scheduleMeal(c,2,"lunch","17:30");scheduleMeal(c,3,"dinner","20:30");scheduleWater(c);}
 public static void scheduleMeal(Context c,int m,String key,String def){SharedPreferences sp=c.getSharedPreferences("md_diet",Context.MODE_PRIVATE);String t=sp.getString("time_"+key,def);String[] p=t.split(":");if(p.length!=2)return;int h,mi;try{h=Integer.parseInt(p[0]);mi=Integer.parseInt(p[1]);}catch(Exception e){return;}Calendar cal=Calendar.getInstance();cal.set(Calendar.HOUR_OF_DAY,h);cal.set(Calendar.MINUTE,mi);cal.set(Calendar.SECOND,0);cal.set(Calendar.MILLISECOND,0);if(cal.getTimeInMillis()<=System.currentTimeMillis())cal.add(Calendar.DAY_OF_YEAR,1);Intent i=new Intent(c,AlarmReceiver.class);i.putExtra("type","meal");i.putExtra("mealIndex",m);PendingIntent pi=PendingIntent.getBroadcast(c,1000+m,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);((AlarmManager)c.getSystemService(Context.ALARM_SERVICE)).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,cal.getTimeInMillis(),pi);}
 public static void scheduleWater(Context c){SharedPreferences sp=c.getSharedPreferences("md_diet",Context.MODE_PRIVATE);Intent i=new Intent(c,AlarmReceiver.class);i.putExtra("type","water");PendingIntent pi=PendingIntent.getBroadcast(c,5001,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(!sp.getBoolean("water_enabled",false)){am.cancel(pi);return;}Calendar cal=Calendar.getInstance();cal.add(Calendar.HOUR_OF_DAY,2);am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,cal.getTimeInMillis(),pi);}
}
